name: Deploy events Service

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      KEYCLOAK_SECRET: ${{ secrets.KEYCLOAK_SECRET }}
      EVENT_SERVICE_BASE_URL: https://benevolo.de/api/event-service

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.OWNER_PASSWORD }}

    - name: Set env variables for dev environment
      if: github.ref == 'refs/heads/develop'
      run: |
          echo "EVENT_SERVICE_BASE_URL=https://dev.benevolo.de/api/event-service" >> $GITHUB_ENV

    - name: Set env variables for prod environment
      if: github.ref == 'refs/heads/main'
      run: |
        echo "EVENT_SERVICE_BASE_URL=https://benevolo.de/api/event-service" >> $GITHUB_ENV

    - name: Build and push prod Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker compose build
        docker compose push

    - name: Build and push dev Docker image
      if: github.ref == 'refs/heads/develop'
      run: |
        docker compose -f docker-compose-dev.yml build
        docker compose -f docker-compose-dev.yml push

  deploymain:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: 'thi24/gitops'
          ref: 'main'
          token:  ${{ secrets.GITOPS }}

    - name: Setup git config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "<>"

    - name: Update docker image version
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.42.1/yq_linux_amd64 -O yq &&\
        chmod +x yq
        NEW_VERSION=${GITHUB_RUN_ID}
        yq e '.services["benevolo.ticket-service"].image = "ghcr.io/thi24/benevolo.ticket-service:'"$NEW_VERSION"'"' -i docker-compose.yml

    - name: Commit and push changes
      run: |
        git commit -a -m "updated by GitHub Actions"
        git push



  deploydev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: 'thi24/gitops-dev'
          ref: 'main'
          token:  ${{ secrets.GITOPS }}

    - name: Setup git config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "<>"

    - name: Update docker image version
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.42.1/yq_linux_amd64 -O yq &&\
        chmod +x yq
        NEW_VERSION=${GITHUB_RUN_ID}
        yq e '.services["dev.benevolo.ticket-service"].image = "ghcr.io/thi24/dev.benevolo.ticket-service:'"$NEW_VERSION"'"' -i docker-compose.yml

    - name: Commit and push changes
      run: |
        git commit -a -m "updated by GitHub Actions"
        git push